// AUTO-GENERATED by scripts/gen-event-table.ts — DO NOT EDIT.
// Run `pnpm gen:events` to regenerate.

export type FieldKind =
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'array'
  | 'unknown'
  | 'literal';

export interface FieldSpec {
  name: string;
  kind: FieldKind;
  required: boolean;
}

export interface EventSpec {
  type: string;
  fields: FieldSpec[];
}

export const GENERATED_FROM_VERSION = '@ag-ui/core@0.0.57';

export const EVENT_TABLE: Record<string, EventSpec> = {
  ACTIVITY_DELTA: {
    type: 'ACTIVITY_DELTA',
    fields: [
      { name: 'activityType', kind: 'string', required: true },
      { name: 'messageId', kind: 'string', required: true },
      { name: 'patch', kind: 'array', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  ACTIVITY_SNAPSHOT: {
    type: 'ACTIVITY_SNAPSHOT',
    fields: [
      { name: 'activityType', kind: 'string', required: true },
      { name: 'content', kind: 'object', required: true },
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'replace', kind: 'boolean', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  CUSTOM: {
    type: 'CUSTOM',
    fields: [
      { name: 'name', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
      { name: 'value', kind: 'unknown', required: false },
    ],
  },
  MESSAGES_SNAPSHOT: {
    type: 'MESSAGES_SNAPSHOT',
    fields: [
      { name: 'messages', kind: 'array', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  RAW: {
    type: 'RAW',
    fields: [
      { name: 'event', kind: 'unknown', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'source', kind: 'string', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_ENCRYPTED_VALUE: {
    type: 'REASONING_ENCRYPTED_VALUE',
    fields: [
      { name: 'encryptedValue', kind: 'string', required: true },
      { name: 'entityId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'subtype', kind: 'unknown', required: true },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_END: {
    type: 'REASONING_END',
    fields: [
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_MESSAGE_CHUNK: {
    type: 'REASONING_MESSAGE_CHUNK',
    fields: [
      { name: 'delta', kind: 'string', required: false },
      { name: 'messageId', kind: 'string', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_MESSAGE_CONTENT: {
    type: 'REASONING_MESSAGE_CONTENT',
    fields: [
      { name: 'delta', kind: 'string', required: true },
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_MESSAGE_END: {
    type: 'REASONING_MESSAGE_END',
    fields: [
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_MESSAGE_START: {
    type: 'REASONING_MESSAGE_START',
    fields: [
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'role', kind: 'literal', required: true },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  REASONING_START: {
    type: 'REASONING_START',
    fields: [
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  RUN_ERROR: {
    type: 'RUN_ERROR',
    fields: [
      { name: 'code', kind: 'string', required: false },
      { name: 'message', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  RUN_FINISHED: {
    type: 'RUN_FINISHED',
    fields: [
      { name: 'outcome', kind: 'unknown', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'result', kind: 'unknown', required: false },
      { name: 'runId', kind: 'string', required: true },
      { name: 'threadId', kind: 'string', required: true },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  RUN_STARTED: {
    type: 'RUN_STARTED',
    fields: [
      { name: 'input', kind: 'object', required: false },
      { name: 'parentRunId', kind: 'string', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'runId', kind: 'string', required: true },
      { name: 'threadId', kind: 'string', required: true },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  STATE_DELTA: {
    type: 'STATE_DELTA',
    fields: [
      { name: 'delta', kind: 'array', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  STATE_SNAPSHOT: {
    type: 'STATE_SNAPSHOT',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'snapshot', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  STEP_FINISHED: {
    type: 'STEP_FINISHED',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'stepName', kind: 'string', required: true },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  STEP_STARTED: {
    type: 'STEP_STARTED',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'stepName', kind: 'string', required: true },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TEXT_MESSAGE_CHUNK: {
    type: 'TEXT_MESSAGE_CHUNK',
    fields: [
      { name: 'delta', kind: 'string', required: false },
      { name: 'messageId', kind: 'string', required: false },
      { name: 'name', kind: 'string', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'role', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TEXT_MESSAGE_CONTENT: {
    type: 'TEXT_MESSAGE_CONTENT',
    fields: [
      { name: 'delta', kind: 'string', required: true },
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TEXT_MESSAGE_END: {
    type: 'TEXT_MESSAGE_END',
    fields: [
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TEXT_MESSAGE_START: {
    type: 'TEXT_MESSAGE_START',
    fields: [
      { name: 'messageId', kind: 'string', required: true },
      { name: 'name', kind: 'string', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'role', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  THINKING_END: {
    type: 'THINKING_END',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  THINKING_START: {
    type: 'THINKING_START',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'title', kind: 'string', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  THINKING_TEXT_MESSAGE_CONTENT: {
    type: 'THINKING_TEXT_MESSAGE_CONTENT',
    fields: [
      { name: 'delta', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  THINKING_TEXT_MESSAGE_END: {
    type: 'THINKING_TEXT_MESSAGE_END',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  THINKING_TEXT_MESSAGE_START: {
    type: 'THINKING_TEXT_MESSAGE_START',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TOOL_CALL_ARGS: {
    type: 'TOOL_CALL_ARGS',
    fields: [
      { name: 'delta', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'toolCallId', kind: 'string', required: true },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TOOL_CALL_CHUNK: {
    type: 'TOOL_CALL_CHUNK',
    fields: [
      { name: 'delta', kind: 'string', required: false },
      { name: 'parentMessageId', kind: 'string', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'toolCallId', kind: 'string', required: false },
      { name: 'toolCallName', kind: 'string', required: false },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TOOL_CALL_END: {
    type: 'TOOL_CALL_END',
    fields: [
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'toolCallId', kind: 'string', required: true },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TOOL_CALL_RESULT: {
    type: 'TOOL_CALL_RESULT',
    fields: [
      { name: 'content', kind: 'string', required: true },
      { name: 'messageId', kind: 'string', required: true },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'role', kind: 'literal', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'toolCallId', kind: 'string', required: true },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
  TOOL_CALL_START: {
    type: 'TOOL_CALL_START',
    fields: [
      { name: 'parentMessageId', kind: 'string', required: false },
      { name: 'rawEvent', kind: 'unknown', required: false },
      { name: 'timestamp', kind: 'number', required: false },
      { name: 'toolCallId', kind: 'string', required: true },
      { name: 'toolCallName', kind: 'string', required: true },
      { name: 'type', kind: 'literal', required: true },
    ],
  },
};

export const EVENT_TYPES: readonly string[] = [
  'ACTIVITY_DELTA',
  'ACTIVITY_SNAPSHOT',
  'CUSTOM',
  'MESSAGES_SNAPSHOT',
  'RAW',
  'REASONING_ENCRYPTED_VALUE',
  'REASONING_END',
  'REASONING_MESSAGE_CHUNK',
  'REASONING_MESSAGE_CONTENT',
  'REASONING_MESSAGE_END',
  'REASONING_MESSAGE_START',
  'REASONING_START',
  'RUN_ERROR',
  'RUN_FINISHED',
  'RUN_STARTED',
  'STATE_DELTA',
  'STATE_SNAPSHOT',
  'STEP_FINISHED',
  'STEP_STARTED',
  'TEXT_MESSAGE_CHUNK',
  'TEXT_MESSAGE_CONTENT',
  'TEXT_MESSAGE_END',
  'TEXT_MESSAGE_START',
  'THINKING_END',
  'THINKING_START',
  'THINKING_TEXT_MESSAGE_CONTENT',
  'THINKING_TEXT_MESSAGE_END',
  'THINKING_TEXT_MESSAGE_START',
  'TOOL_CALL_ARGS',
  'TOOL_CALL_CHUNK',
  'TOOL_CALL_END',
  'TOOL_CALL_RESULT',
  'TOOL_CALL_START',
];
