/**
 * Generates `src/core/events/event-table.generated.ts` from the Zod schemas
 * exported by `@ag-ui/core`.
 *
 * `@ag-ui/core` is a devDependency and is imported HERE AND NOWHERE ELSE. The
 * runtime core must stay free of it so the extension does not ship a Zod copy
 * and does not break when upstream changes its schema internals.
 *
 * Zod v3 introspection (verified against zod@3.25.76 + @ag-ui/core@0.0.57):
 *   - each `*EventSchema` export is a ZodObject exposing `.shape`
 *   - every field carries `._def.typeName` ('ZodString', 'ZodOptional', ...)
 *   - `field.isOptional()` reports optionality
 *   - a ZodOptional/ZodDefault wraps its inner schema at `._def.innerType`
 *   - the discriminant is `shape.type`, a ZodLiteral whose `._def.value` is the
 *     event-type string. `BaseEventSchema` is the one export that fails this
 *     check (its `type` is a ZodNativeEnum) and is correctly skipped.
 *
 * Output is deterministic: event types sorted alphabetically, fields sorted by
 * name, so re-running produces a byte-identical file.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as core from '@ag-ui/core';

type FieldKind =
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'array'
  | 'unknown'
  | 'literal';

interface ZodDefLike {
  typeName?: string;
  innerType?: ZodLike;
  value?: unknown;
}

interface ZodLike {
  _def?: ZodDefLike;
  shape?: Record<string, ZodLike>;
  isOptional?: () => boolean;
}

interface FieldSpec {
  name: string;
  kind: FieldKind;
  required: boolean;
}

interface EventSpec {
  type: string;
  fields: FieldSpec[];
}

const KIND_BY_TYPE_NAME: Record<string, FieldKind> = {
  ZodString: 'string',
  ZodEnum: 'string',
  ZodNativeEnum: 'string',
  ZodNumber: 'number',
  ZodBoolean: 'boolean',
  ZodObject: 'object',
  ZodRecord: 'object',
  ZodArray: 'array',
  ZodLiteral: 'literal',
};

const WRAPPERS = new Set(['ZodOptional', 'ZodDefault']);

/** Strip ZodOptional / ZodDefault wrappers to reach the value schema. */
function unwrap(field: ZodLike): ZodLike {
  let node = field;
  for (let depth = 0; depth < 10; depth += 1) {
    const typeName = node._def?.typeName;
    const inner = node._def?.innerType;
    if (typeName !== undefined && WRAPPERS.has(typeName) && inner) {
      node = inner;
      continue;
    }
    return node;
  }
  return node;
}

function kindOf(field: ZodLike): FieldKind {
  const typeName = unwrap(field)._def?.typeName;
  if (typeName === undefined) return 'unknown';
  return KIND_BY_TYPE_NAME[typeName] ?? 'unknown';
}

function collectSpecs(): EventSpec[] {
  const exports = core as unknown as Record<string, ZodLike | undefined>;
  const specs: EventSpec[] = [];

  for (const exportName of Object.keys(exports)) {
    if (!/^(.+)EventSchema$/.test(exportName)) continue;

    const schema = exports[exportName];
    const shape = schema?.shape;
    if (!shape || typeof shape !== 'object') continue;

    // The discriminant must be a ZodLiteral; BaseEventSchema (ZodNativeEnum) is skipped.
    const typeField = shape.type;
    if (typeField?._def?.typeName !== 'ZodLiteral') continue;
    const eventType = typeField._def?.value;
    if (typeof eventType !== 'string') continue;

    const fields: FieldSpec[] = Object.keys(shape)
      .sort()
      .map((name) => {
        const field = shape[name] as ZodLike;
        return {
          name,
          kind: kindOf(field),
          required: field.isOptional?.() !== true,
        };
      });

    specs.push({ type: eventType, fields });
  }

  specs.sort((a, b) => (a.type < b.type ? -1 : a.type > b.type ? 1 : 0));
  return specs;
}

function render(specs: EventSpec[], coreVersion: string): string {
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/gen-event-table.ts — DO NOT EDIT.');
  lines.push('// Run `pnpm gen:events` to regenerate.');
  lines.push('');
  lines.push('export type FieldKind =');
  lines.push("  | 'string'");
  lines.push("  | 'number'");
  lines.push("  | 'boolean'");
  lines.push("  | 'object'");
  lines.push("  | 'array'");
  lines.push("  | 'unknown'");
  lines.push("  | 'literal';");
  lines.push('');
  lines.push('export interface FieldSpec {');
  lines.push('  name: string;');
  lines.push('  kind: FieldKind;');
  lines.push('  required: boolean;');
  lines.push('}');
  lines.push('');
  lines.push('export interface EventSpec {');
  lines.push('  type: string;');
  lines.push('  fields: FieldSpec[];');
  lines.push('}');
  lines.push('');
  lines.push(`export const GENERATED_FROM_VERSION = '@ag-ui/core@${coreVersion}';`);
  lines.push('');
  lines.push('export const EVENT_TABLE: Record<string, EventSpec> = {');
  for (const spec of specs) {
    lines.push(`  ${spec.type}: {`);
    lines.push(`    type: '${spec.type}',`);
    lines.push('    fields: [');
    for (const field of spec.fields) {
      lines.push(
        `      { name: '${field.name}', kind: '${field.kind}', required: ${field.required} },`,
      );
    }
    lines.push('    ],');
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export const EVENT_TYPES: readonly string[] = [');
  for (const spec of specs) lines.push(`  '${spec.type}',`);
  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const requireFromHere = createRequire(import.meta.url);
  const corePkg = requireFromHere('@ag-ui/core/package.json') as { version: string };

  const specs = collectSpecs();
  if (specs.length === 0) {
    throw new Error('gen-event-table: no *EventSchema exports found in @ag-ui/core');
  }

  const outPath = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../src/core/events/event-table.generated.ts',
  );
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, render(specs, corePkg.version), 'utf8');

  process.stdout.write(
    `gen-event-table: wrote ${specs.length} event types from @ag-ui/core@${corePkg.version}\n`,
  );
}

main();
